drop schema ezpower;
create schema ezpower;
use ezpower;
-- Create Tables
CREATE TABLE USER (
    User_id INT,
    username VARCHAR(20) NOT NULL,
    address VARCHAR(50) NOT NULL,
    phone_number BIGINT NOT NULL,
    date_joined TIMESTAMP,
    Is_active BOOLEAN,
    Is_staff BOOLEAN
);

CREATE TABLE ACCOUNT (
    Account_id BIGINT,
    User_id INT NOT NULL,
    Account_bal DECIMAL NOT NULL
);

CREATE TABLE METER (
    Meter_id BIGINT,
    location VARCHAR(255) NOT NULL,
    units DECIMAL NOT NULL,
    User_id INT
);

CREATE TABLE TOKEN (
    Token_id BIGINT,
    units DECIMAL NOT NULL,
    Used BOOLEAN NOT NULL,
    Meter_id BIGINT
);

CREATE TABLE TRANSACTION (
    Transaction_id BIGINT,
    trans_time DATETIME NOT NULL,
    Amount DECIMAL NOT NULL,
    Token_id BIGINT NOT NULL,
    Account_id BIGINT NOT NULL
);

-- Add PRIMARY KEY constraints
ALTER TABLE USER ADD PRIMARY KEY (user_id);
ALTER TABLE ACCOUNT ADD PRIMARY KEY (Account_id);
ALTER TABLE METER ADD PRIMARY KEY (Meter_id);
ALTER TABLE TOKEN ADD PRIMARY KEY (Token_id);
ALTER TABLE TRANSACTION ADD PRIMARY KEY (Transaction_id);

-- Add FOREIGN KEY constraints
ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (User_id) REFERENCES USER(User_id);
ALTER TABLE METER ADD CONSTRAINT FK_METER_USER FOREIGN KEY (User_id) REFERENCES USER(User_id);
ALTER TABLE TOKEN ADD CONSTRAINT FK_TOKEN_METER FOREIGN KEY (Meter_id) REFERENCES METER(Meter_id);
ALTER TABLE TRANSACTION ADD CONSTRAINT FK_TRANSACTION_TOKEN FOREIGN KEY (Token_id) REFERENCES TOKEN(Token_id);
ALTER TABLE TRANSACTION ADD CONSTRAINT FK_TRANSACTION_ACCOUNT FOREIGN KEY (Account_id) REFERENCES ACCOUNT(Account_id);

-- Add UNIQUE KEY constraints
ALTER TABLE ACCOUNT
ADD CONSTRAINT UNIQUE (User_id);

ALTER TABLE TRANSACTION
ADD CONSTRAINT UNIQUE (Token_id);




